### ISSUE TITLE
Badger App phones home

### ISSUE THREAD

**Issue by sonicou** [EFForg/privacybadgerfirefox-legacy#816]
After installing the app via the firefox add on page, I noticed that with every start of firefox there were tcp connections already started before I opened any url.
Since normally there would be absolutely no traffic unless site are opened that menas badger causes this traffic, phoning home. Tested this several times and as soon as I deaktived badger the traffic stopped.

To be clear it is not relevant what this is used for, this behaviour is unacceptable.

The connections used the following ips: 52.38.97.120, 151.101.12.201

**Comment by 6a68** [comment]
@sonicou Hi, I don't think these network requests are anything to worry about.

If you enable and open the [browser toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox), then install Privacy Badger, then look at the browser toolbox network tab, you'll see that the addon fetches some files from the EFF website. These are named cookieblocklist.txt, domain_exception_list.json, and dnt-policies.json, and contain just the sort of content you'd expect. You can examine the file contents in the browser toolbox (the 'response' tab in the right panel of the network tab), or copy and paste the URLs into your browser's address bar.

Here's a screenshot from my browser toolbox:
<img width="978" alt="screen shot 2016-11-12 at 1 35 04 pm" src="https://cloud.githubusercontent.com/assets/96396/20241178/d689dc82-a8dc-11e6-98a0-20785f0676cf.png">

You can also search the code for each of those file names to see how they're used. In particular, [this comment](https://github.com/EFForg/privacybadgerfirefox/blob/0c24e87b06e58e66583a05ecdf2be8dcf8dd59dc/lib/policyCheck.js#L23) and [the following comment](https://github.com/EFForg/privacybadgerfirefox/blob/0c24e87b06e58e66583a05ecdf2be8dcf8dd59dc/lib/policyCheck.js#L27) explain that those files are re-fetched daily and whenever Firefox starts up.

**Comment by sonicou** [comment]
I'm sure they are needed and the intent is not malicious but thats actually not the point.

Having a browser extension start a network connection every time the application is started is a very bad design choice and also leaks the information about this extension being installed to anyone listening on the network. There is no reason to do that. Having a 24 hour fetch or rather a weekly update is usually more then enought and practiced by many other apps that take privacy seriously.

**Comment by 6a68** [comment]
Cool, it sounds like you think weekly pings would be preferable. You could submit a PR to change the ping frequency, and see what feedback you get :-)

**Comment by sonicou** [comment]
Great idea. Just did that.
I believe this should solve the issue: #819

**Comment by cooperq** [comment]
Hi @sonicou 
I'm not convinced that checking for updates on startup presents more of a fingerprinting problem than checking for them every 24 hours. I do it on startup because some people don't consistently leave their browser open for 24 hours straight (much less a week!) and might then never receive the update. 

I would consider checking for updates on startup and then again 1 week later. Or storing the update time in local storage and then only checking once per week. But I'm still not clear on how that actually limits fingerprinting. Could you clarify that for me? 

Also, we have now switched to https://github.com/eff.org/privacybadger as the codebase for both firefox and chrome as of the next version of privacy badger. Would you mind posting your issue there instead? (and making any future pull requests against that repo instead?)

**Comment by sonicou** [comment]
It was not my intent to do the update after having the app run for 24 hours, but I assumed that this would still trigger 24 or 48 hours after the last check.

Some people open and close their browser hunderts of times a day and every time badger connects to the eff servers. That is not appropriate for a privacy app.

**Comment by cooperq** [comment]
@sonicou that is a fair point. I would accept a pull request that ran the check every 24 hours instead of every time the browser is started. But please make that PR against https://github.com/EFForg/privacybadger instead.

**Comment by jaredhirsch** [comment]
@sonicou @cooperq Hey, I might instead suggest: "if it's been 24 hours since last check, then check on startup".

There have historically been issues with Firefox users having very stale addons precisely because addon updating uses a "once per day, if FF is open" update model, and some users tend to be offline at the magic time.

**Comment by jaredhirsch** [comment]
hmm, or maybe, "if it's been > 24 hours since last check, check on startup, otherwise check once a day, if online". le sigh

**Comment by cooperq** [comment]
What I was thinking was something like (pseudocode):
```
on startup and once per hour do:
  if time_since_last_update >= 24_hours:
    do_update()
```
